title: Pavlidis' Portfolio
description: >
  **Charis Pavlidis' Portfolio**<br />
  Computer Engineer
copyright: Untitled
sass:
  sass_dir: assets/sass
url: http://localhost:4000
linkedin_username: "charispavlidis"
github_username:  "pavlidischrs"
feed_icon: rss
email: "pavlidis.chrs@gmail.com"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics-ua: UA-108436907-1

#-------------------------------
